n = 6;

%The x values of our function 
y = [1960 1970 1980 1990 2000 2010];

%The f(x) values of our function 
f = [179323 203302 226542 249633 281422 308746];

%Creates a 6 x 6 matrix  
F = zeros(n,n);
F(:,1) = f;

%Iterates through each row in the matrix calulating the divided difference
%for each entry 
for i = 2:n 
    for j = 2:i
        F(i,j) = (F(i,j-1)-F(i-1,j-1))/(y(i)-y(i-j+1));
    end
end

%Will help simplify Pn equation into one that is comprehendable
syms x;

%Creates a 6x6 matrix 
Pn = F(n,n);

%Utilizes the entries from the matrix and calculates the polynomial
%expression that is an approximate of the function at any given value (x)
for i = n-1:-1:1
    Pn = Pn*(x-y(i)) + F(i,i);
end

sympref('FloatingPointOutput', true)

%Reduces Pn into a simple expression
simplify(Pn)

%Runs the expression generated by Pn with an x values to give an
%approximation of what the f(x) value of the function is
subs(Pn,2014)
subs(Pn,1950)

%scatter(y,f); hold on;
%ezplot(x,Pn);xlim([0,5])